baseURL = "http://aperta.lu/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "FIFTY-ONE Luxembourg-APERTA"
theme = "beautifulhugo"

[[menu.main]]
    name = "Activités"
    url = ""
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 2

[[menu.main]]
    name = "Accès Membres"
    url = "https://cms.aperta.lu/"
    weight = 3


[Params]
  hometitle = "Amitié, Estime, Tolérance"
  subtitle = "FIFTY-ONE Luxembourg-APERTA"
  mainSections = ["post","posts"]
  logo = "img/logo-aperta.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2 Jan 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = true

[[Params.bigimg]]
  src = "img/aperta-bg.png"
  desc = ""

[Author]
  name = "aperta"
  website = ""
  email = "info@aperta.lu"
