DefaultContentLanguage = "fr"
baseURL = "https://aperta.lu/"
languageCode = "fr-fr"
theme = "beautifulhugo"
title = "FIFTY-ONE Luxembourg-APERTA"
[Author]
email = "pst@libre.lu"
name = "pst"
website = "https://pst.libre.lu"
[Params]
comments = false
commit = false
dateFormat = "2 Jan 2006"
delayDisqus = false
favicon = "img/favicon.ico"
hideAuthor = true
hometitle = "Amitié, Estime, Tolérance"
logo = "img/logo-aperta.png"
mainSections = ["post", "posts"]
readingTime = false
rss = false
showRelatedPosts = false
socialShare = true
subtitle = "FIFTY-ONE Luxembourg-APERTA"
useHLJS = true
wordCount = false
[[Params.bigimg]]
desc = ""
src = "img/aperta-bg.png"
[[menu.main]]
name = "Accès Membres"
url = "https://cms.aperta.lu/"
weight = 3
[[menu.main]]
name = "Contact"
url = "page/contact/"
weight = 2
[[menu.main]]
name = "Activités"
weight = 1
